### ISSUE TITLE
Network Mapped Drives

### ISSUE THREAD

**Issue by IFireflyl** [swiszczoo/winpinator#17]
Winpinator is currently unable to access network mapped drives. I have a NAS where I store files, and it would be more convenient to be able to copy those files from the NAS to my Steam Deck directly instead of moving the files to my computer first and then moving it to my Steam Deck. Is this something that could possibly be supported in the future?

**Comment by swiszczoo** [comment]
Hi, I just did a quick test and it appears that sending from network drives, as well as setting a network drive as the save folder works flawlessly, at least on my machine (Windows 10). To be honest, this feature wasn't planned but why not support it, if it works out of the box. So we can assume that there is a bug that occured on your computer. Can you provide more details? 

+ What operating system do you use? 
+ Are you trying to send single files or entire directories? 
+ What are the filenames of the files you try to send (if it's not secret, of course)? 
+ Which method of sending files do you use (drag-and-drop, clicking "Send file(s)" button, right-clicking a file and selecting `Send to` > `Winpinator`)? 
+ What do you see (an error, the transfer is marked immediately as failed, Winpinator ignores files from NAS completely and nothing happens)?

**Comment by IFireflyl** [comment]
Hey @swiszczoo, it looks like the issue must have been on my end. Either my PC was being dumb or, and this is the more likely scenario, I was suffering from temporary regional blindness. I confirmed that I can access my NAS. I'll close this issue out. I apologize for bothering you, but I appreciate the quick response!
