### ISSUE TITLE
Winpinator failing to get correct IP address?

### ISSUE THREAD

**Issue by dagleykd** [swiszczoo/winpinator#23]
Hi!

I have Warpinator on my 4 Linux machines, and just installed Winpinator to try on my Win10 desktop. Winpinator launches and can see my other Linux machines, but claims there is no connection. Also, none of my Linux machines can see the machine with Winpinator?

I've tried restarting the program and the Windows computer it's installed on and Winpinator still claims the same thing - no connection to the other machines...?

I noticed that the IP address listed at the bottom-right in Winpinator isn't correct? Instead of the 192.168.*.* address it should be getting from the ethernet card my Win10 desktop is plugged into, the IP address that Winpinator is listing itself as using is 169.254.*.* ?

Is there a way to change the settings or re-force Winpinator to use a different IP?

Thanks for all the hard work on this project! :)

**Comment by swiszczoo** [comment]
Hi! Currently, automatic network interface selection is quite broken, but there is an option to manually select the correct one. See my comment on #11.

**Comment by dagleykd** [comment]
> Hi! Currently, automatic network interface selection is quite broken, but there is an option to manually select the correct one. See my comment on #11.

Thanks friend, had not noticed that in the settings as I didn't even tough that dropdown menu assuming it should just stay on Automatic! All working now, cheers and thanks for the hard work! :)
